[2025-08-27T17:37:05.113+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-27T17:37:05.119+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_simple.predict manual__2025-08-27T17:36:40.617220+00:00 [queued]>
[2025-08-27T17:37:05.121+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_simple.predict manual__2025-08-27T17:36:40.617220+00:00 [queued]>
[2025-08-27T17:37:05.122+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-08-27T17:37:05.127+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): predict> on 2025-08-27 17:36:40.617220+00:00
[2025-08-27T17:37:05.129+0000] {standard_task_runner.py:72} INFO - Started process 469 to run task
[2025-08-27T17:37:05.131+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline_simple', 'predict', 'manual__2025-08-27T17:36:40.617220+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/instructions.py', '--cfg-path', '/tmp/tmp9i8a874j']
[2025-08-27T17:37:05.132+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask predict
[2025-08-27T17:37:05.148+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline_simple.predict manual__2025-08-27T17:36:40.617220+00:00 [running]> on host 73d5ca51174b
[2025-08-27T17:37:05.167+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ml_pipeline_simple' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T17:36:40.617220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T17:36:40.617220+00:00'
[2025-08-27T17:37:05.168+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-27T17:37:05.173+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-27T17:37:05.173+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/scripts/predict.py']
[2025-08-27T17:37:05.176+0000] {subprocess.py:86} INFO - Output:
[2025-08-27T17:37:05.731+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-27T17:37:05.731+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/predict.py", line 26, in <module>
[2025-08-27T17:37:05.731+0000] {subprocess.py:93} INFO -     out.to_csv("results/predictions.csv", index=False)
[2025-08-27T17:37:05.731+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/generic.py", line 3902, in to_csv
[2025-08-27T17:37:05.731+0000] {subprocess.py:93} INFO -     return DataFrameRenderer(formatter).to_csv(
[2025-08-27T17:37:05.731+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -     csv_formatter.save()
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/formats/csvs.py", line 247, in save
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -     with get_handle(
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 739, in get_handle
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -     check_parent_directory(str(handle))
[2025-08-27T17:37:05.732+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/common.py", line 604, in check_parent_directory
[2025-08-27T17:37:05.733+0000] {subprocess.py:93} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-08-27T17:37:05.733+0000] {subprocess.py:93} INFO - OSError: Cannot save file into a non-existent directory: 'results'
[2025-08-27T17:37:05.789+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-27T17:37:05.793+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-27T17:37:05.795+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline_simple, task_id=predict, run_id=manual__2025-08-27T17:36:40.617220+00:00, execution_date=20250827T173640, start_date=20250827T173705, end_date=20250827T173705
[2025-08-27T17:37:05.800+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-27T17:37:05.800+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task predict (Bash command failed. The command returned a non-zero exit code 1.; 469)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-27T17:37:05.829+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-27T17:37:05.834+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T17:37:05.834+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
