[2025-08-27T17:13:26.533+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-27T17:13:26.537+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_simple.preprocess_train manual__2025-08-27T17:08:22.128814+00:00 [queued]>
[2025-08-27T17:13:26.539+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_simple.preprocess_train manual__2025-08-27T17:08:22.128814+00:00 [queued]>
[2025-08-27T17:13:26.539+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-08-27T17:13:26.544+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): preprocess_train> on 2025-08-27 17:08:22.128814+00:00
[2025-08-27T17:13:26.546+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-08-27T17:13:26.548+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ml_pipeline_simple', 'preprocess_train', 'manual__2025-08-27T17:08:22.128814+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/instructions.py', '--cfg-path', '/tmp/tmpu8wvjyf_']
[2025-08-27T17:13:26.549+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask preprocess_train
[2025-08-27T17:13:26.562+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline_simple.preprocess_train manual__2025-08-27T17:08:22.128814+00:00 [running]> on host ce5676400cb3
[2025-08-27T17:13:26.580+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ml_pipeline_simple' AIRFLOW_CTX_TASK_ID='preprocess_train' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T17:08:22.128814+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-27T17:08:22.128814+00:00'
[2025-08-27T17:13:26.581+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-08-27T17:13:26.587+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-27T17:13:26.587+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/airflow/scripts/preprocess_training.py']
[2025-08-27T17:13:26.590+0000] {subprocess.py:86} INFO - Output:
[2025-08-27T17:13:26.915+0000] {subprocess.py:93} INFO - /opt/airflow/scripts/preprocess_training.py:45: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.16666666666666666' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
[2025-08-27T17:13:26.921+0000] {subprocess.py:93} INFO -   mmkp.loc[(mmkp['Team'] == 'Wisconsin') & (mmkp['Year'] == 2002), 'Winner'] = 1/6
[2025-08-27T17:13:27.002+0000] {subprocess.py:93} INFO - /opt/airflow/scripts/preprocess_training.py:875: SettingWithCopyWarning:
[2025-08-27T17:13:27.002+0000] {subprocess.py:93} INFO - A value is trying to be set on a copy of a slice from a DataFrame.
[2025-08-27T17:13:27.002+0000] {subprocess.py:93} INFO - Try using .loc[row_indexer,col_indexer] = value instead
[2025-08-27T17:13:27.002+0000] {subprocess.py:93} INFO - 
[2025-08-27T17:13:27.002+0000] {subprocess.py:93} INFO - See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-08-27T17:13:27.003+0000] {subprocess.py:93} INFO -   greaterthanNine['Var1 -Target'] = greaterthanNine['Variable 1'].map(target_corr)
[2025-08-27T17:13:27.004+0000] {subprocess.py:93} INFO - /opt/airflow/scripts/preprocess_training.py:876: SettingWithCopyWarning:
[2025-08-27T17:13:27.006+0000] {subprocess.py:93} INFO - A value is trying to be set on a copy of a slice from a DataFrame.
[2025-08-27T17:13:27.006+0000] {subprocess.py:93} INFO - Try using .loc[row_indexer,col_indexer] = value instead
[2025-08-27T17:13:27.006+0000] {subprocess.py:93} INFO - 
[2025-08-27T17:13:27.006+0000] {subprocess.py:93} INFO - See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-08-27T17:13:27.006+0000] {subprocess.py:93} INFO -   greaterthanNine['Var2 C-Target'] = greaterthanNine['Variable 2'].map(target_corr)
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -   File "/opt/airflow/scripts/preprocess_training.py", line 881, in <module>
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -     greaterthanNine = pd.DataFrame(greaterthanNine[['Variable 1', 'Var1 C-Target', 'Variable 2', 'Var2 C-Target', 'Correlation']])
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -                                    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 3899, in __getitem__
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -     indexer = self.columns._get_indexer_strict(key, "columns")[1]
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -     self._raise_if_missing(keyarr, indexer, axis_name)
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO -     raise KeyError(f"{not_found} not in index")
[2025-08-27T17:13:27.007+0000] {subprocess.py:93} INFO - KeyError: "['Var1 C-Target'] not in index"
[2025-08-27T17:13:27.031+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-27T17:13:27.035+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-27T17:13:27.037+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ml_pipeline_simple, task_id=preprocess_train, run_id=manual__2025-08-27T17:08:22.128814+00:00, execution_date=20250827T170822, start_date=20250827T171326, end_date=20250827T171327
[2025-08-27T17:13:27.042+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-08-27T17:13:27.043+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task preprocess_train (Bash command failed. The command returned a non-zero exit code 1.; 105)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-27T17:13:27.072+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-27T17:13:27.078+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-27T17:13:27.080+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
